name = "alr"
description = "Command-line tool from the Alire project"

version = "1.3.0-dev"

authors = ["Alejandro R. Mosteo", "Fabien Chouteau", "Pierre-Marie de Rodat"]
maintainers = ["alejandro@mosteo.com", "chouteau@adacore.com"]
maintainers-logins = ["mosteo", "Fabien-Chouteau"]

# At some point we should have a separate alire/libalire crate for use of
# alire.gpr only. For now this crate is not intended as a dependency but to be
# used to build alr.
auto-gpr-with = false
project-files = ["alr.gpr"]
executables = ["alr"]

[[depends-on]]
aaa = "~0.2.7"
ada_toml = "~0.3"
ajunitgen = "^1.0.1"
ansiada = "^1.0"
clic = "~0.3"
gnatcoll = "^21"
minirest = "~0.2"
optional = "~0.1"
semantic_versioning = "^3.0"
simple_logging = "^2.0"
si_units = "~0.2"
stopwatch = "~0.1"
toml_slicer = "~0.1"
uri_ada = "^2.0"
spdx = "~0.2"

# For some reason static-pic is causing problems in CLIC
[gpr-set-externals]
CLIC_LIBRARY_TYPE="static"

# Building alr requires the explicit setting of this variable
[gpr-set-externals."case(os)"]
macos   = { OS = "macOS" }

# Some dependencies require precise versions during the development cycle:
[[pins]]
aaa = { url = "https://github.com/mosteo/aaa.git", commit = "906d9eaf4fb8efabfbc3d8cfb34d04ceec340e13" }
ada_toml = { url = "https://github.com/pmderodat/ada-toml.git", commit = "2a671ffb1039a036f2bb68bdc88afc8d3dc68c10" }
ajunitgen = { url = "https://github.com/mosteo/ajunitgen.git", commit = "e5d01db5e7834d15c4066f0a8e33d780deae3cc9" }
ansiada = { url = "https://github.com/mosteo/ansi-ada.git", commit = "acf9afca3afe1f8b8843c061f3cef860d7567307" }
clic = { url = "https://github.com/alire-project/clic.git", commit = "185519d65b089c3238e24cfe87f1d22db1f3e0d9" }
gnatcoll = { url = "https://github.com/alire-project/gnatcoll-core.git", commit = "92bb91130a9ec628b4c48b7ef9fe7f24d9dc25fa" }
minirest = { url = "https://github.com/mosteo/minirest.git", commit = "4550aa356d55b9cd55f26acd34701f646021c5ff" }
optional = { url = "https://github.com/mosteo/optional.git", commit = "0c7d20c0c8b48ccb6b25fb648d48382e598c25c3" }
semantic_versioning = { url = "https://github.com/alire-project/semantic_versioning.git", commit = "fe4e72e40786589a66d53662639f894fcdb3419c" }
simple_logging = { url = "https://github.com/alire-project/simple_logging.git", commit = "02a7de7568af6af7cedd1048901fae8e9477b1d9" }
stopwatch = { url = "https://github.com/mosteo/stopwatch.git", commit = "86e7302d29f360f98f568b6015755229949b2194" }
toml_slicer = { url = "https://github.com/mosteo/toml_slicer.git", commit = "8b9dff0f450394b07ea71f0eb9b39d9c20e21f9c" }
uri_ada = { url = "https://github.com/mosteo/uri-ada.git", commit = "b61eba59099b3ab39e59e228fe4529927f9e849e" }
