.TH ALR-GET 1 "Aug 3, 2022" "Alire 1.2" "Alire manual"
.nh
.ad l
.SH NAME
alr-get \- Fetches a crate release
.\"
.SH SYNOPSIS
.sp
\fIalr get\fP [options] <crate>[allowed versions]
.\"
.SH OPTIONS
.TP 5
-b, --build
Build after download
.TP 5
--dirname
Display deployment folder
.TP 5
-o, --only
Retrieve requested crate only, without dependencies
.\"
.SH GLOBAL OPTIONS
.TP 5
-c, --config=\fIARG\fP
Override configuration folder location
.TP 5
-f, --force
Keep going after a recoverable troublesome situation
.TP 5
-h, --help
Display general or command-specific help
.TP 5
-n, --non-interactive
Assume default answers for all user prompts
.TP 5
--no-color
Disables colors in output
.TP 5
--no-tty
Disables control characters in output
.TP 5
--prefer-oldest
Prefer oldest versions instead of newest when resolving dependencies
.TP 5
--version
Displays version and exits
.TP 5
-q
Limit output to errors
.TP 5
-v
Be more verbose (use twice for extra detail)
.TP 5
-d, --debug[]
Enable debug-specific log messages
.\"
.SH DESCRIPTION
Retrieve a crate, in the case of regular ones, or install a system package
provided by the platform. A regular crate is deployed under an immediate
folder with naming 'name_version_hash'.
.PP
Version selection syntax (global policy applies within the allowed version
subsets):
.PP
crate        	Newest/oldest version
.br
crate=version	Exact version
.br
crate^version	Major-compatible version
.br
crate~version	Minor-compatible version

.SH SEE ALSO
\fIalr(1)\fR, \fIalr-index(1)\fR, \fIalr-init(1)\fR, \fIalr-pin(1)\fR, \fIalr-search(1)\fR, \fIalr-show(1)\fR, \fIalr-update(1)\fR, \fIalr-with(1)\fR, \fIgprbuild(1)\fR
.SH AUTHOR
Generated with generate-man from Alire execution
